#!/bin/bash

if [[ $1 == "configure" ]]; then

    [ -e /etc/default/xbmc ] || mv /var/tmp/xbmc /etc/default/xbmc

    if [ -e /var/tmp/xbmc ]; then
        OPTIONS=$(grep -E "^\w+=.+" /var/tmp/xbmc)
        ADVANCED_OPTIONS="USER HOME GROUP DAEMON DAEMON_ARGS DAEMON_LIRC PATH ZTEMPXBMC DEBUG"
        ALL_OPTIONS="$OPTIONS $ADVANCED_OPTIONS"

        for option in $ALL_OPTIONS; do
            opt_name=${option%%=*}
            if grep -q "^${opt_name}=" /etc/default/xbmc; then
                old_opt_value=$(grep ^${opt_name}= /etc/default/xbmc | tr "'" "\"")
                if grep -q "^${opt_name}=" /var/tmp/xbmc; then
                    eval $(echo "sed -i 's%$option%$old_opt_value%' /var/tmp/xbmc")
                else
                    echo $old_opt_value >> /var/tmp/xbmc
                fi
            fi
        done

        mv /var/tmp/xbmc /etc/default/xbmc
    fi
    :

    if [ -n "$(dpkg --get-selections raspi-config 2>/dev/null)" ]; then 
        
        [ -e /tmp/xbmc.force.auto ] || echo manual >> /etc/init/xbmc.override
        rm -f /tmp/xbmc.force.auto
    fi

elif [ $1 = triggered ]; then

    :
#        if [ -f "/tmp/startxbmc" ]; then
#                [ -e /etc/init/xbmc.conf ] || service xbmc start > /dev/null 2>&1
#                [ -e /etc/init/xbmc.conf ] && start -n xbmc
#                rm /tmp/startxbmc
#        fi

fi

exit 0
