#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

:

    if [ -e /etc/init/xbmc-preload.conf ]; then
        { [ ! -e /etc/init/xbmc.override ] || ! grep -qw manual /etc/init/xbmc.override; } && touch /tmp/xbmc.force.auto
    fi

fi

exit 0
